import org.code.neighborhood.*;

public class paintBackground extends PainterPlus {

public void background(String color) {
  setPaint(500);
 paint(color);
    while(canMove()){
      move();
      paint(color);
    }
    turnRight();
    move();
    paint(color);
    turnRight();
    while(canMove()){
      move();
      paint(color);
    }
    turnLeft();
    move();
    paint(color);
    turnLeft();
    while(canMove()){
      move();
      paint(color);
    }
    turnRight();
    move();
    paint(color);
    turnRight();
    while(canMove()){
      move();
      paint(color);
    }
    turnLeft();
    move();
    paint(color);
    turnLeft();
        while(canMove()){
      move();
      paint(color);
    }
    turnRight();
    move();
    paint(color);
    turnRight();
    while(canMove()){
      move();
      paint(color);
    }
    turnLeft();
    move();
    paint(color);
    turnLeft();
        while(canMove()){
      move();
      paint(color);
    }
    turnRight();
    move();
    paint(color);
    turnRight();
    while(canMove()){
      move();
      paint(color);
    }
    turnLeft();
    move();
    paint(color);
    turnLeft();
        while(canMove()){
      move();
      paint(color);
    }
    turnRight();
    move();
    paint(color);
    turnRight();
    while(canMove()){
      move();
      paint(color);
    }
    turnLeft();
    move();
    paint(color);
    turnLeft();
        while(canMove()){
      move();
      paint(color);
    }
    turnRight();
    move();
    paint(color);
    turnRight();
    while(canMove()){
      move();
      paint(color);
    }
 
}
}

